### ISSUE TITLE
What does this output log mean ?

### ISSUE THREAD

**Issue by vegeta2102** [plaidev/karte-technical-support#4]
Hi,
When I send event to Karte for tracking view, there was some abnormal log has been output in Console Log tab.
What does this log mean ? 
It'd be helpful if you could describe in detail because I am confused that there maybe effect to my application ...

Thanks !

```
2019-01-30 12:49:55.512 23480-23480/myProject E/Karte.OverlayVM: Unknown callbackName:karte-tracker-callback://visibility?data=%7B%22state%22%3A%22visible%22%7D&t=1548820195454
    java.lang.IllegalArgumentException: no such enum object for the callback: visibility
        at io.karte.android.tracker.OverlayViewModel$TrackerJsCallback.of(OverlayViewModel.java:59)
        at io.karte.android.tracker.OverlayViewModel.shouldOverrideUrlLoading(OverlayViewModel.java:212)
        at io.karte.android.tracker.OverlayView$1.shouldOverrideUrlLoading(OverlayView.java:249)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at apM.a(SourceFile:1)
        at xq.b(SourceFile:81)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(SourceFile:172)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:379)
        at android.os.Looper.loop(Looper.java:144)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by takaaki7** [comment]
We've fixed this issue. Now you can check no error logs are printed.
You don't need to upgrade SDK because the OTA update was applied to the Javascript module.
